### ISSUE TITLE
QA_Order-of-the-menu_Permeability Experiment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/soil-mechanics-and-foundation-engineering-iiith#98]
Defect Description :
The order of the menu items for this experiment is not in desired order. Need to correct the order to "Introduction, Theory, Objective, Manual, Procedure, Experiment, Quizzes, Further readings and Feedback".

Actual Result :
The order of the menu items for this experiment is not in desired order. The order of the menu items are given as "Introduction, Theory, Objective, Experiment, Manual, Quizzes, Procedure, Further readings, Feedback"

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sm_i43](https://cloud.githubusercontent.com/assets/13479177/26486967/f2d1268e-421a-11e7-9270-235b6241ed76.png)

**Comment by sravanthimodepu** [comment]
The order of the menu items arranged as given"Introduction, Theory, Objective, Manual, Procedure, Experiment, Quizzes, Further readings and Feedback". Hence issue is resolved

**Comment by BSravanthi** [comment]
Order of the menu is still not in desired order. Hence re opening the issue. 

![qa_oe_sm_i61](https://user-images.githubusercontent.com/13479177/27725065-49bc4e28-5d92-11e7-8646-e3d817e6ca48.png)

**Comment by sravanthimodepu** [comment]
Fixed.
![perm-menu](https://user-images.githubusercontent.com/11156924/27830199-f0d970d4-60e2-11e7-8d3f-91bf7ac17d92.png)

**Comment by BSravanthi** [comment]
Closed #98
